import { http, HttpResponse } from 'msw';
import type { components } from '../../api/schema';

type Schemas = components['schemas'];

const claysBroken1000: Schemas['TrophyOut'] = {
  code: 'clays_broken:3',
  family: 'clays_broken',
  name: 'Clays Broken',
  description: 'Lifetime targets broken (the sum of every round’s score).',
  category: 'milestone',
  art_key: 'clays_broken',
  metal: 'silver',
  level: 3,
  threshold: 1000,
  label: '1,000 clays broken',
  repeatable: false,
  holders: 65,
  rarity_pct: 19.6,
  last_awarded: '2026-09-13',
};

export const achievementsFixture: Schemas['AchievementsOut'] = {
  recent_total: 1,
  n_shooters: 332,
  trophies: [
    claysBroken1000,
    {
      code: 'first_win',
      family: 'first_win',
      name: 'First Win',
      description: 'Top score of the day (ties count) with at least 5 shooters.',
      category: 'competition',
      art_key: 'first_win',
      metal: null,
      level: null,
      threshold: null,
      label: null,
      repeatable: false,
      holders: 120,
      rarity_pct: 36.1,
      last_awarded: '2026-09-13',
    },
    {
      code: 'rain',
      family: 'rain',
      name: 'Rain Shooter',
      description: 'Shot on a day with 0.02 in or more of rain between 10:00 and 12:00.',
      category: 'conditions',
      art_key: 'rain',
      metal: null,
      level: null,
      threshold: null,
      label: null,
      repeatable: false,
      holders: 0,
      rarity_pct: 0,
      last_awarded: null,
    },
  ],
  recent: [
    {
      shooter_id: 12,
      display_name: 'Hadley, Ike',
      code: 'clays_broken:3',
      family: 'clays_broken',
      name: 'Clays Broken',
      label: '1,000 clays broken',
      metal: 'silver',
      art_key: 'clays_broken',
      event_date: '2026-09-13',
      round_id: null,
      details: { value: 1004, threshold: 1000 },
    },
  ],
};

export const trophyDetailFixture: Schemas['AchievementDetailOut'] = {
  trophy: claysBroken1000,
  holders: [
    {
      shooter_id: 12,
      display_name: 'Hadley, Ike',
      shooter_status: 'member',
      first_date: '2024-05-05',
      count: 1,
      dates: ['2024-05-05'],
    },
    {
      shooter_id: 40,
      display_name: 'Yoder, Gavin',
      shooter_status: 'deceased',
      first_date: '2025-02-02',
      count: 1,
      dates: ['2025-02-02'],
    },
  ],
};

export const shooterAchievementsFixture: Schemas['ShooterAchievementsOut'] = {
  shooter_id: 12,
  display_name: 'Hadley, Ike',
  earned: [
    {
      code: 'clays_broken:1',
      family: 'clays_broken',
      name: 'Clays Broken',
      description: 'Lifetime targets broken (the sum of every round’s score).',
      category: 'milestone',
      art_key: 'clays_broken',
      metal: 'bronze',
      level: 1,
      label: '100 clays broken',
      first_date: '2023-04-02',
      count: 1,
      dates: ['2023-04-02'],
    },
    {
      code: 'welcome_back',
      family: 'welcome_back',
      name: 'Welcome Back',
      description: 'Returned after 180 or more days away.',
      category: 'calendar',
      art_key: 'welcome_back',
      metal: null,
      level: null,
      label: null,
      first_date: '2024-03-03',
      count: 2,
      dates: ['2024-03-03', '2025-04-06'],
    },
  ],
  progress: [
    {
      code: 'clays_broken',
      name: 'Clays Broken',
      description: 'Lifetime targets broken (the sum of every round’s score).',
      category: 'milestone',
      art_key: 'clays_broken',
      value: 1742,
      earned_level: 3,
      earned_metal: 'silver',
      earned_label: '1,000 clays broken',
      next_level: 4,
      next_threshold: 2500,
      next_label: '2,500 clays broken',
      next_metal: 'gold',
      fraction: 0.6968,
    },
    {
      code: 'years_active',
      name: 'Years Active',
      description: 'Calendar years with at least one Sunday shot.',
      category: 'milestone',
      art_key: 'years_active',
      value: 7,
      earned_level: 4,
      earned_metal: 'platinum',
      earned_label: '7 years',
      next_level: null,
      next_threshold: null,
      next_label: null,
      next_metal: null,
      fraction: 1,
    },
    {
      code: 'events',
      name: 'Events Attended',
      description: 'Sundays shot.',
      category: 'milestone',
      art_key: 'events',
      value: 48,
      earned_level: 3,
      earned_metal: 'bronze',
      earned_label: '25 events',
      next_level: 4,
      next_threshold: 50,
      next_label: '50 events',
      next_metal: 'bronze',
      fraction: 0.96,
    },
    {
      code: 'round_score',
      name: 'Round Score',
      description: 'Your best single round.',
      category: 'scoring',
      art_key: 'round_score',
      value: 44,
      earned_level: 3,
      earned_metal: 'silver',
      earned_label: '40 in one round',
      next_level: 4,
      next_threshold: 45,
      next_label: '45 in one round',
      next_metal: 'gold',
      fraction: 0.9778,
    },
    {
      code: 'iron_streak',
      name: 'Iron Streak',
      description:
        'Consecutive held events attended; attendance-only dates neither extend nor break it.',
      category: 'milestone',
      art_key: 'iron_streak',
      value: 2,
      earned_level: 0,
      earned_metal: null,
      earned_label: null,
      next_level: 1,
      next_threshold: 4,
      next_label: '4 straight events',
      next_metal: 'bronze',
      fraction: 0.5,
    },
  ],
  locked: [
    {
      code: 'mudder',
      name: 'Mudder',
      description: 'Broke 40 or more in the rain.',
      category: 'conditions',
      art_key: 'mudder',
      rarity_pct: 3.3,
    },
  ],
};

export const eventAchievementsFixture: Schemas['EventAchievementsOut'] = {
  event_date: '2026-09-13',
  awards: [
    {
      shooter_id: 12,
      display_name: 'Hadley, Ike',
      code: 'station_top_gun',
      family: 'station_top_gun',
      name: 'Station Top Gun',
      label: null,
      metal: null,
      art_key: 'station_top_gun',
      event_date: '2026-09-13',
      round_id: null,
      details: { stations: [5] },
    },
    {
      shooter_id: 7,
      display_name: 'McGinnis, Alvin',
      code: 'events:5',
      family: 'events',
      name: 'Events Attended',
      label: '100 events',
      metal: 'silver',
      art_key: 'events',
      event_date: '2026-09-13',
      round_id: null,
      details: { value: 100, threshold: 100 },
    },
  ],
};

export const handlers = [
  http.get('*/api/achievements', () => HttpResponse.json(achievementsFixture)),
  http.get('*/api/achievements/:code', () => HttpResponse.json(trophyDetailFixture)),
  http.get('*/api/shooters/:id/achievements', () => HttpResponse.json(shooterAchievementsFixture)),
  http.get('*/api/events/:date/achievements', () => HttpResponse.json(eventAchievementsFixture)),
];
