// Generated by tools/trophy_art/cli.py build. Do not edit by hand.
export const trophyArt: Record<string, { src: string; src128: string }> = {
  above_average_3: {
    src: '/trophies/above_average_3.webp',
    src128: '/trophies/above_average_3@128.webp',
  },
  all_weather: {
    src: '/trophies/all_weather.webp',
    src128: '/trophies/all_weather@128.webp',
  },
  anniversary_1: {
    src: '/trophies/anniversary_1.webp',
    src128: '/trophies/anniversary_1@128.webp',
  },
  anniversary_5: {
    src: '/trophies/anniversary_5.webp',
    src128: '/trophies/anniversary_5@128.webp',
  },
  'big_year-bronze': {
    src: '/trophies/big_year-bronze.webp',
    src128: '/trophies/big_year-bronze@128.webp',
  },
  'big_year-gold': {
    src: '/trophies/big_year-gold.webp',
    src128: '/trophies/big_year-gold@128.webp',
  },
  'big_year-silver': {
    src: '/trophies/big_year-silver.webp',
    src128: '/trophies/big_year-silver@128.webp',
  },
  both_disciplines: {
    src: '/trophies/both_disciplines.webp',
    src128: '/trophies/both_disciplines@128.webp',
  },
  'clays_broken-bronze': {
    src: '/trophies/clays_broken-bronze.webp',
    src128: '/trophies/clays_broken-bronze@128.webp',
  },
  'clays_broken-diamond': {
    src: '/trophies/clays_broken-diamond.webp',
    src128: '/trophies/clays_broken-diamond@128.webp',
  },
  'clays_broken-gold': {
    src: '/trophies/clays_broken-gold.webp',
    src128: '/trophies/clays_broken-gold@128.webp',
  },
  'clays_broken-platinum': {
    src: '/trophies/clays_broken-platinum.webp',
    src128: '/trophies/clays_broken-platinum@128.webp',
  },
  'clays_broken-silver': {
    src: '/trophies/clays_broken-silver.webp',
    src128: '/trophies/clays_broken-silver@128.webp',
  },
  'clays_thrown-bronze': {
    src: '/trophies/clays_thrown-bronze.webp',
    src128: '/trophies/clays_thrown-bronze@128.webp',
  },
  'clays_thrown-diamond': {
    src: '/trophies/clays_thrown-diamond.webp',
    src128: '/trophies/clays_thrown-diamond@128.webp',
  },
  'clays_thrown-gold': {
    src: '/trophies/clays_thrown-gold.webp',
    src128: '/trophies/clays_thrown-gold@128.webp',
  },
  'clays_thrown-platinum': {
    src: '/trophies/clays_thrown-platinum.webp',
    src128: '/trophies/clays_thrown-platinum@128.webp',
  },
  'clays_thrown-silver': {
    src: '/trophies/clays_thrown-silver.webp',
    src128: '/trophies/clays_thrown-silver@128.webp',
  },
  cold: {
    src: '/trophies/cold.webp',
    src128: '/trophies/cold@128.webp',
  },
  comeback: {
    src: '/trophies/comeback.webp',
    src128: '/trophies/comeback@128.webp',
  },
  doubleheader: {
    src: '/trophies/doubleheader.webp',
    src128: '/trophies/doubleheader@128.webp',
  },
  'events-bronze': {
    src: '/trophies/events-bronze.webp',
    src128: '/trophies/events-bronze@128.webp',
  },
  'events-diamond': {
    src: '/trophies/events-diamond.webp',
    src128: '/trophies/events-diamond@128.webp',
  },
  'events-gold': {
    src: '/trophies/events-gold.webp',
    src128: '/trophies/events-gold@128.webp',
  },
  'events-platinum': {
    src: '/trophies/events-platinum.webp',
    src128: '/trophies/events-platinum@128.webp',
  },
  'events-silver': {
    src: '/trophies/events-silver.webp',
    src128: '/trophies/events-silver@128.webp',
  },
  first_win: {
    src: '/trophies/first_win.webp',
    src128: '/trophies/first_win@128.webp',
  },
  four_seasons: {
    src: '/trophies/four_seasons.webp',
    src128: '/trophies/four_seasons@128.webp',
  },
  hardest_station_clean: {
    src: '/trophies/hardest_station_clean.webp',
    src128: '/trophies/hardest_station_clean@128.webp',
  },
  heat: {
    src: '/trophies/heat.webp',
    src128: '/trophies/heat@128.webp',
  },
  'iron_streak-bronze': {
    src: '/trophies/iron_streak-bronze.webp',
    src128: '/trophies/iron_streak-bronze@128.webp',
  },
  'iron_streak-gold': {
    src: '/trophies/iron_streak-gold.webp',
    src128: '/trophies/iron_streak-gold@128.webp',
  },
  'iron_streak-platinum': {
    src: '/trophies/iron_streak-platinum.webp',
    src128: '/trophies/iron_streak-platinum@128.webp',
  },
  'iron_streak-silver': {
    src: '/trophies/iron_streak-silver.webp',
    src128: '/trophies/iron_streak-silver@128.webp',
  },
  joined_club: {
    src: '/trophies/joined_club.webp',
    src128: '/trophies/joined_club@128.webp',
  },
  mudder: {
    src: '/trophies/mudder.webp',
    src128: '/trophies/mudder@128.webp',
  },
  new_year: {
    src: '/trophies/new_year.webp',
    src128: '/trophies/new_year@128.webp',
  },
  perfect_month: {
    src: '/trophies/perfect_month.webp',
    src128: '/trophies/perfect_month@128.webp',
  },
  'personal_bests-bronze': {
    src: '/trophies/personal_bests-bronze.webp',
    src128: '/trophies/personal_bests-bronze@128.webp',
  },
  'personal_bests-gold': {
    src: '/trophies/personal_bests-gold.webp',
    src128: '/trophies/personal_bests-gold@128.webp',
  },
  'personal_bests-silver': {
    src: '/trophies/personal_bests-silver.webp',
    src128: '/trophies/personal_bests-silver@128.webp',
  },
  podium: {
    src: '/trophies/podium.webp',
    src128: '/trophies/podium@128.webp',
  },
  rain: {
    src: '/trophies/rain.webp',
    src128: '/trophies/rain@128.webp',
  },
  'round_score-bronze': {
    src: '/trophies/round_score-bronze.webp',
    src128: '/trophies/round_score-bronze@128.webp',
  },
  'round_score-diamond': {
    src: '/trophies/round_score-diamond.webp',
    src128: '/trophies/round_score-diamond@128.webp',
  },
  'round_score-gold': {
    src: '/trophies/round_score-gold.webp',
    src128: '/trophies/round_score-gold@128.webp',
  },
  'round_score-platinum': {
    src: '/trophies/round_score-platinum.webp',
    src128: '/trophies/round_score-platinum@128.webp',
  },
  'round_score-silver': {
    src: '/trophies/round_score-silver.webp',
    src128: '/trophies/round_score-silver@128.webp',
  },
  'station_cleaner-bronze': {
    src: '/trophies/station_cleaner-bronze.webp',
    src128: '/trophies/station_cleaner-bronze@128.webp',
  },
  'station_cleaner-gold': {
    src: '/trophies/station_cleaner-gold.webp',
    src128: '/trophies/station_cleaner-gold@128.webp',
  },
  'station_cleaner-platinum': {
    src: '/trophies/station_cleaner-platinum.webp',
    src128: '/trophies/station_cleaner-platinum@128.webp',
  },
  'station_cleaner-silver': {
    src: '/trophies/station_cleaner-silver.webp',
    src128: '/trophies/station_cleaner-silver@128.webp',
  },
  station_top_gun: {
    src: '/trophies/station_top_gun.webp',
    src128: '/trophies/station_top_gun@128.webp',
  },
  sub_gauge: {
    src: '/trophies/sub_gauge.webp',
    src128: '/trophies/sub_gauge@128.webp',
  },
  three_bird_shoot: {
    src: '/trophies/clays_thrown-gold.webp',
    src128: '/trophies/clays_thrown-gold@128.webp',
  },
  welcome_back: {
    src: '/trophies/welcome_back.webp',
    src128: '/trophies/welcome_back@128.webp',
  },
  wind: {
    src: '/trophies/wind.webp',
    src128: '/trophies/wind@128.webp',
  },
  'years_active-bronze': {
    src: '/trophies/years_active-bronze.webp',
    src128: '/trophies/years_active-bronze@128.webp',
  },
  'years_active-gold': {
    src: '/trophies/years_active-gold.webp',
    src128: '/trophies/years_active-gold@128.webp',
  },
  'years_active-platinum': {
    src: '/trophies/years_active-platinum.webp',
    src128: '/trophies/years_active-platinum@128.webp',
  },
  'years_active-silver': {
    src: '/trophies/years_active-silver.webp',
    src128: '/trophies/years_active-silver@128.webp',
  },
};
