import { http, HttpResponse } from 'msw';
import type { EventDetail, EventSummary, Meta, ShooterDetail, ShooterRound } from './api';

export const homeMeta: Meta = {
  app_version: 'test',
  data_version: 7,
  first_event_date: '2018-12-30',
  last_event_date: '2026-09-27',
  first_score_date: '2020-01-05',
  last_score_date: '2026-09-27',
  n_events: 360,
  n_scored_events: 311,
  n_held_events: 310,
  n_station_events: 2,
  n_rounds: 7480,
  n_shooters: 332,
  last_rebuild_at: '2026-09-27T19:01:04Z',
};

const unmodelled = {
  gauge_class: null,
  shooter_status: 'member',
  expected: null,
  residual: null,
} as const;

/** 2026-09-27: a tie at 49 for first, then 48. */
export const latestEvent: EventDetail = {
  kind: 'regular',
  label: null,
  target_total: 50,
  event_date: '2026-09-27',
  round_type: 'sporting',
  round_type_source: 'none',
  head_count: 23,
  has_scores: true,
  has_stations: false,
  results_complete: true,
  n_rounds: 23,
  n_shooters: 23,
  median: 39,
  mean: 39.13,
  stdev: 6.864,
  top_score: 49,
  difficulty: -1.4,
  results: [
    {
      ...unmodelled,
      round_id: 7458,
      shooter_id: 30,
      display_name: 'Finnegan, Stanton',
      name_key: 'finnegan stanton',
      ordinal: 1,
      score: 49,
      adjusted: 10,
      event_rank: 1,
      is_best_round: true,
      percentile: 0.977,
      mu_before: 38.2,
      mu_after: 39.0,
      rating_delta: 0.8,
    },
    {
      ...unmodelled,
      round_id: 7457,
      shooter_id: 31,
      display_name: 'Stockton, Ethan',
      name_key: 'stockton ethan',
      ordinal: 1,
      score: 49,
      adjusted: 10,
      event_rank: 1,
      is_best_round: true,
      percentile: 0.977,
      mu_before: 40.1,
      mu_after: 40.6,
      rating_delta: 0.5,
    },
    {
      ...unmodelled,
      round_id: 7459,
      shooter_id: 32,
      display_name: 'Grimsby, Gregor',
      name_key: 'grimsby gregor',
      ordinal: 1,
      score: 48,
      adjusted: 9,
      event_rank: 3,
      is_best_round: true,
      percentile: 0.909,
      mu_before: 41.0,
      mu_after: 41.2,
      rating_delta: 0.2,
    },
  ],
  weather: null,
  stations: null,
  notables: [],
  vs_prev: null,
};

const scoredWeek = { has_scores: true, results_complete: true, condition: null } as const;

/** 2026 season sample. 2026-09-27's head count is blanked on purpose (its 23 shooters stand in for turnout). */
export const seasonEvents: EventSummary[] = [
  {
    kind: 'regular',
    label: null,
    target_total: 50,
    ...scoredWeek,
    event_date: '2026-09-13',
    round_type: 'super_sporting',
    round_type_source: 'stations',
    has_stations: true,
    head_count: 13,
    n_rounds: 13,
    n_shooters: 13,
    median: 34,
    top_score: 42,
    difficulty: 2.1,
    winners: [{ shooter_id: 12, display_name: 'Nordquist, Sherman', score: 42 }],
  },
  {
    kind: 'regular',
    label: null,
    target_total: 50,
    ...scoredWeek,
    event_date: '2026-09-27',
    round_type: 'sporting',
    round_type_source: 'none',
    has_stations: false,
    head_count: null,
    n_rounds: 23,
    n_shooters: 23,
    median: 39,
    top_score: 49,
    difficulty: -1.4,
    winners: [
      { shooter_id: 31, display_name: 'Stockton, Ethan', score: 49 },
      { shooter_id: 30, display_name: 'Finnegan, Stanton', score: 49 },
    ],
  },
  {
    kind: 'regular',
    label: null,
    target_total: 50,
    ...scoredWeek,
    event_date: '2026-09-06',
    round_type: 'super_sporting',
    round_type_source: 'stations',
    has_stations: true,
    head_count: 24,
    n_rounds: 24,
    n_shooters: 24,
    median: 36,
    top_score: 48,
    difficulty: 0.3,
    winners: [{ shooter_id: 32, display_name: 'Grimsby, Gregor', score: 48 }],
  },
  {
    kind: 'regular',
    label: null,
    target_total: 50,
    event_date: '2026-01-04',
    round_type: 'sporting',
    round_type_source: 'none',
    has_stations: false,
    has_scores: false,
    results_complete: false,
    head_count: 12,
    n_rounds: 0,
    n_shooters: 0,
    median: null,
    top_score: null,
    difficulty: null,
    condition: null,
    winners: [],
  },
];

export const meDetail: ShooterDetail = {
  shooter_id: 3,
  display_name: 'Hadley, Ike',
  status: 'member',
  deceased: false,
  first_event: '2020-01-05',
  last_event: '2026-09-27',
  left_censored: true,
  current_mu: 35.1,
  current_var: 3.9,
  stats: {
    n_rounds: 267,
    n_events: 267,
    avg_score: 35.31,
    median_score: 36,
    best_score: 45,
    avg_adjusted: -0.45,
    wins: 2,
    podiums: 14,
    avg_percentile: 0.487,
  },
  odometer: {
    clays_thrown: 13350,
    clays_broken: 9427,
    hit_pct: 0.706,
    rounds: 267,
    events: 267,
    years_active: 7,
    current_streak: 2,
    longest_streak: 31,
    favorite_month: 6,
    trophies: 0,
  },
  pbs: [{ scope: 'overall', key: 'all', score: 45, event_date: '2022-04-03', round_id: 3850 }],
};

const roundDefaults = {
  gauge_class: null,
  status: 'member',
  expected: null,
  residual: null,
  condition: null,
} as const;

/** Hadley's last two rounds (fixture scores and field medians; ranks and ratings illustrative). */
export const meRounds: ShooterRound[] = [
  {
    ...roundDefaults,
    round_id: 7471,
    event_date: '2026-09-27',
    ordinal: 1,
    score: 37,
    round_type: 'sporting',
    field_median: 39,
    adjusted: -2,
    event_rank: 16,
    is_best_round: true,
    percentile: 0.32,
    mu_before: 35.0,
    mu_after: 35.1,
  },
  {
    ...roundDefaults,
    round_id: 7450,
    event_date: '2026-09-13',
    ordinal: 1,
    score: 34,
    round_type: 'super_sporting',
    field_median: 34,
    adjusted: 0,
    event_rank: 7,
    is_best_round: true,
    percentile: 0.5,
    mu_before: 35.3,
    mu_after: 35.0,
  },
];

// Default handler (home owns /api/meta); branch-free, exercised by routes.test.tsx.
export const handlers = [http.get('*/api/meta', () => HttpResponse.json(homeMeta))];
