"""trophy-art CLI (run from tools/trophy_art):
generate → sheet → (the user picks) → select … → build. `check` confirms manifest coverage."""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import Any

from client import GenerationSpec, ImagenClient, ImagenError, ImagenUnreachable
from contact_sheet import build_sheet
from manifest import METALS, load_manifest
from process import medallion

HERE = Path(__file__).resolve().parent
DEFAULT_IMAGEN_URL = "https://imagen.thehalf.io"
_HEADER = "// Generated by tools/trophy_art/cli.py build. Do not edit by hand.\n"
_DECL = "export const trophyArt: Record<string, { src: string; src128: string }> = "


def _ts_key(stem: str) -> str:
    return stem if stem.isidentifier() else f"'{stem}'"


def render_manifest_ts(stems: Sequence[str], files: Mapping[str, str] | None = None) -> str:
    """The file in the form the frontend's `prettier --check` accepts (quoteProps as-needed, printWidth 100):
    keys are quoted only when they are not identifiers (a `-metal` stem), and every entry is expanded."""
    if not stems:
        return _HEADER + _DECL + "{};\n"
    shown = files or {}
    entries = [
        f"  {_ts_key(s)}: {{\n    src: '/trophies/{shown.get(s, s)}.webp',\n"
        f"    src128: '/trophies/{shown.get(s, s)}@128.webp',\n  }},\n"
        for s in sorted(stems)
    ]
    return _HEADER + _DECL + "{\n" + "".join(entries) + "};\n"


def _read_selection(path: Path) -> dict[str, dict[str, Any]]:
    selection: dict[str, dict[str, Any]] = json.loads(path.read_text())
    return selection


def _generate(args: argparse.Namespace) -> int:
    # Credentials are optional: an imagen with no login-capable account serves anonymous callers.
    # Half a pair is a typo, not a choice, so it stops before any request is made.
    username = os.environ.get("IMAGEN_USERNAME") or None
    password = os.environ.get("IMAGEN_PASSWORD") or None
    if (username is None) != (password is None):
        print("set both IMAGEN_USERNAME and IMAGEN_PASSWORD, or neither", file=sys.stderr)
        return 2
    targets = [t for t in load_manifest(args.manifest) if args.only is None or t.art_key == args.only]
    if not targets:
        print(f"no manifest target has art_key {args.only}", file=sys.stderr)
        return 2
    client = ImagenClient(os.environ.get("IMAGEN_URL") or DEFAULT_IMAGEN_URL)
    failures = 0
    try:
        if username is not None and password is not None:
            client.login(username, password)
        for target in targets:
            for seed in target.seeds:
                path = args.out / "candidates" / target.stem / f"{seed}.png"
                if path.exists():
                    continue
                spec = GenerationSpec(
                    art_key=target.art_key,
                    metal=target.metal,
                    prompt=target.prompt,
                    negative=target.negative,
                    model=target.model,
                    seed=seed,
                    size=target.size,
                    attempt=args.retry,
                    steps=target.steps,
                    cfg=target.cfg,
                    sampler=target.sampler,
                    scheduler=target.scheduler,
                )
                try:
                    data = client.generate(spec)
                except ImagenUnreachable:
                    raise
                except ImagenError as exc:
                    failures += 1
                    print(f"{target.stem} seed {seed}: {exc}", file=sys.stderr)
                    continue
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
                print(f"{target.stem} seed {seed}: saved {path}")
    except ImagenError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    finally:
        client.close()
    return 1 if failures else 0


def _sheet(args: argparse.Namespace) -> int:
    candidates = args.out / "candidates"
    if not candidates.is_dir():
        print("no candidates yet: run generate first", file=sys.stderr)
        return 1
    sheet = args.out / "contact_sheet.html"
    sheet.write_text(build_sheet(candidates))
    print(f"wrote {sheet}")
    return 0


def _select(args: argparse.Namespace) -> int:
    metal = None if args.metal == "-" else str(args.metal)
    if metal is not None and metal not in METALS:
        print(f"metal must be one of {', '.join(METALS)} or '-'", file=sys.stderr)
        return 2
    if (args.candidate is None) == (args.reuse is None):
        print("give either a candidate seed or --reuse STEM", file=sys.stderr)
        return 2
    stem = args.art_key if metal is None else f"{args.art_key}-{metal}"
    selection = _read_selection(args.selection)
    if args.reuse is not None:
        source = selection.get(args.reuse)
        if source is None or "seed" not in source:
            print(f"--reuse needs an existing picked selection, not {args.reuse}", file=sys.stderr)
            return 1
        selection[stem] = {"art_key": args.art_key, "metal": metal, "reuse": args.reuse}
        print(f"selected {stem} reusing {args.reuse}")
    else:
        candidate = args.out / "candidates" / stem / f"{args.candidate}.png"
        if not candidate.exists():
            print(f"no candidate {candidate}", file=sys.stderr)
            return 1
        selection[stem] = {"art_key": args.art_key, "metal": metal, "seed": args.candidate}
        print(f"selected {stem} seed {args.candidate}")
    args.selection.write_text(json.dumps(selection, indent=2, sort_keys=True) + "\n")
    return 0


def _file_stems(selection: dict[str, dict[str, Any]]) -> dict[str, str] | None:
    """Each key's built-file stem: its own, or its reused source's. None when a reuse has no source."""
    files: dict[str, str] = {}
    for stem, pick in selection.items():
        source = pick.get("reuse", stem)
        if source != stem and "seed" not in selection.get(source, {}):
            print(f"{stem} reuses {source}, which has no picked candidate", file=sys.stderr)
            return None
        files[stem] = source
    return files


def _write_manifest(selection: dict[str, dict[str, Any]], files: dict[str, str], repo_root: Path) -> None:
    generated = repo_root / "frontend" / "src" / "features" / "achievements" / "trophyArt.gen.ts"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(render_manifest_ts(list(selection), files))


def _build(args: argparse.Namespace) -> int:
    """Writes WebP pairs for picked candidates; a reused key gets no art of its own, only a manifest entry
    that points at its source's files."""
    selection = _read_selection(args.selection)
    files = _file_stems(selection)
    if files is None:
        return 1
    public = args.repo_root / "frontend" / "public" / "trophies"
    public.mkdir(parents=True, exist_ok=True)
    for stem, pick in sorted(selection.items()):
        if "reuse" in pick:
            continue
        candidate = args.out / "candidates" / stem / f"{pick['seed']}.png"
        if not candidate.exists():
            print(f"missing candidate {candidate}", file=sys.stderr)
            return 1
        png = candidate.read_bytes()
        (public / f"{stem}.webp").write_bytes(medallion(png, 256))
        (public / f"{stem}@128.webp").write_bytes(medallion(png, 128))
    _write_manifest(selection, files, args.repo_root)
    print(f"built {len(selection)} trophies into {public}")
    return 0


def _manifest(args: argparse.Namespace) -> int:
    """Regenerates trophyArt.gen.ts from selection.json and the WebP files already built, no candidates."""
    selection = _read_selection(args.selection)
    files = _file_stems(selection)
    if files is None:
        return 1
    public = args.repo_root / "frontend" / "public" / "trophies"
    missing = [
        f"{public / f'{source}{suffix}.webp'}"
        for source in sorted(set(files.values()))
        for suffix in ("", "@128")
        if not (public / f"{source}{suffix}.webp").exists()
    ]
    for path in missing:
        print(f"missing built file {path}", file=sys.stderr)
    if missing:
        return 1
    _write_manifest(selection, files, args.repo_root)
    print(f"wrote the manifest for {len(selection)} trophies")
    return 0


def _check(args: argparse.Namespace) -> int:
    wanted = {(str(k), None if m is None else str(m)) for k, m in json.loads(args.keys.read_text())}
    have = {(t.art_key, t.metal) for t in load_manifest(args.manifest)}
    missing = sorted(wanted - have, key=lambda km: (km[0], km[1] or ""))
    for art_key, metal in missing:
        print(f"missing manifest entry: {art_key} {metal or '-'}")
    if missing:
        return 1
    print(f"all {len(wanted)} art targets are in the manifest")
    return 0


COMMANDS: dict[str, Callable[[argparse.Namespace], int]] = {
    "generate": _generate,
    "sheet": _sheet,
    "select": _select,
    "build": _build,
    "manifest": _manifest,
    "check": _check,
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="trophy-art", description="Sunday Clays trophy art pipeline (dev-only).")
    parser.add_argument("--out", type=Path, default=HERE / "out")
    parser.add_argument("--manifest", type=Path, default=HERE / "manifest.yaml")
    parser.add_argument("--selection", type=Path, default=HERE / "selection.json")
    sub = parser.add_subparsers(dest="command", required=True)
    generate = sub.add_parser("generate", help="create candidates on imagen (resumable; logs in if credentials set)")
    generate.add_argument("--only", metavar="ART_KEY")
    generate.add_argument(
        "--retry",
        type=int,
        default=0,
        metavar="N",
        help="idempotency-key suffix: rerunning replays a failed or canceled seed, so pass N=1, 2, ... to "
        "re-render it (default 0 = the C12 key)",
    )
    sub.add_parser("sheet", help="write out/contact_sheet.html")
    select = sub.add_parser("select", help="record the user's pick")
    select.add_argument("art_key")
    select.add_argument("metal", help="bronze|silver|gold|platinum|diamond, or - for a one-off")
    select.add_argument("candidate", type=int, nargs="?", help="the picked candidate's seed")
    select.add_argument(
        "--reuse",
        metavar="STEM",
        help="use another key's picked art instead of a candidate, e.g. clays_thrown-gold",
    )
    build = sub.add_parser("build", help="write WebP medallions and trophyArt.gen.ts")
    build.add_argument("--repo-root", type=Path, default=HERE.parent.parent)
    manifest = sub.add_parser("manifest", help="rewrite trophyArt.gen.ts from selection.json and the built files")
    manifest.add_argument("--repo-root", type=Path, default=HERE.parent.parent)
    check = sub.add_parser("check", help="verify the manifest covers a JSON list of [art_key, metal|null]")
    check.add_argument("keys", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return COMMANDS[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
